export const PORTFOLIO_DETAILS = [
  {
    id: 1,
    date: "September 2019",
    title: "Seraph Staion",
    desktopImg: "/portfolio/desktop/image-seraph.jpg",
    tabletImg: "/portfolio/tablet/image-seraph.jpg",
    mobileImg: "/portfolio/mobile/image-seraph.jpg",
  },
  {
    id: 2,
    date: "August 2017",
    title: "Eebox Building",
    desktopImg: "/portfolio/desktop/image-eebox.jpg",
    tabletImg: "/portfolio/tablet/image-eebox.jpg",
    mobileImg: "/portfolio/mobile/image-eebox.jpg",
  },
  {
    id: 3,
    date: "March 2017",
    title: "Federal II Tower",
    desktopImg: "/portfolio/desktop/image-federal.jpg",
    tabletImg: "/portfolio/tablet/image-federal.jpg",
    mobileImg: "/portfolio/mobile/image-federal.jpg",
  },
  {
    id: 4,
    date: "January 2016",
    title: "Project Del Sol",
    desktopImg: "/portfolio/desktop/image-del-sol.jpg",
    tabletImg: "/portfolio/tablet/image-del-sol.jpg",
    mobileImg: "/portfolio/mobile/image-del-sol.jpg",
  },
  {
    id: 5,
    date: "October 2015",
    title: "Le Prototype",
    desktopImg: "/portfolio/desktop/image-prototype.jpg",
    tabletImg: "/portfolio/tablet/image-prototype.jpg",
    mobileImg: "/portfolio/mobile/image-prototype.jpg",
  },
  {
    id: 6,
    date: "April 2015",
    title: "228B Tower",
    desktopImg: "/portfolio/desktop/image-228b.jpg",
    tabletImg: "/portfolio/tablet/image-228b.jpg",
    mobileImg: "/portfolio/mobile/image-228b.jpg",
  },
  {
    id: 7,
    date: "December 2013",
    title: "Grand Edelweiss Hotel",
    desktopImg: "/portfolio/desktop/image-edelweiss.jpg",
    tabletImg: "/portfolio/tablet/image-edelweiss.jpg",
    mobileImg: "/portfolio/mobile/image-edelweiss.jpg",
  },
  {
    id: 8,
    date: "August 2012",
    title: "Netcry Tower",
    desktopImg: "/portfolio/desktop/image-netcry.jpg",
    tabletImg: "/portfolio/tablet/image-netcry.jpg",
    mobileImg: "/portfolio/mobile/image-netcry.jpg",
  },
  {
    id: 9,
    date: "January 2012",
    title: "Hypers",
    desktopImg: "/portfolio/desktop/image-hypers.jpg",
    tabletImg: "/portfolio/tablet/image-hypers.jpg",
    mobileImg: "/portfolio/mobile/image-hypers.jpg",
  },
  {
    id: 10,
    date: "March 2011",
    title: "SXIV Tower",
    desktopImg: "/portfolio/desktop/image-sxiv.jpg",
    tabletImg: "/portfolio/tablet/image-sxiv.jpg",
    mobileImg: "/portfolio/mobile/image-sxiv.jpg",
  },
  {
    id: 11,
    date: "September 2010",
    title: "Trinity Bank Tower",
    desktopImg: "/portfolio/desktop/image-trinity.jpg",
    tabletImg: "/portfolio/tablet/image-trinity.jpg",
    mobileImg: "/portfolio/mobile/image-trinity.jpg",
  },
  {
    id: 12,
    date: "February 2008",
    title: "Project Paramour",
    desktopImg: "/portfolio/desktop/image-paramour.jpg",
    tabletImg: "/portfolio/tablet/image-paramour.jpg",
    mobileImg: "/portfolio/mobile/image-paramour.jpg",
  },
];